memo_index:
    path: /memo
    controller: App\Controller\MemoController::index
    methods: [GET]

memo_create:
    path: /memo/create
    controller: App\Controller\MemoController::create
    methods: [GET, POST]

memo_edit:
    path: /memo/{id}/edit
    controller: App\Controller\MemoController::edit
    methods: [GET, POST]

memo_delete:
    path: /memo/{id}/delete
    controller: App\Controller\MemoController::delete
    methods: [GET, POST]
